cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl -y
  - set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - perl -V
  - cd %APPVEYOR_BUILD_FOLDER%
  - cpanm --verbose --installdeps .

build_script:
  - perl Makefile.PL
  - gmake

test_script:
  - gmake test
